# This is what was first generated by /dev agent
# It has 2 issues:
# - It is not sending the expected json format to the API/lambda function 
#    => That means the /dev generation is not consistent, but I guess we can improve that with more accurate prompt
# - It is not using the /prod/feedbacks endpoint (but /feedbacks only)

import json

def handler(event, context):
    html_content = """
    <!DOCTYPE html>
    <html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>Feedback Form</title>
    </head>
    <body>
        <h1>Feedback Form</h1>
        <form action="/feedbacks" method="post">
            <label for="feedback">Your Feedback:</label><br>
            <textarea id="feedback" name="feedback" rows="4" cols="50"></textarea><br>
            <input type="submit" value="Submit">
        </form>
    </body>
    </html>
    """
    
    return {
        'statusCode': 200,
        'headers': {'Content-Type': 'text/html'},
        'body': html_content
    }